### PR TITLE
fix: resolve round summary upsert issue

### LINKED ISSUE #1070: bug: round summary upsert issue
**Overview**

This is an issue that happens when using the update summary for a round endpoint. If an item already existed in a table, it updating it would violate our key indexes. 

Resolve it by investigating the prisma and database implementation for update round summary handler.

### PR DESCRIPTION
**Pull request by hmrtn**
fixes #1070

### CODE REVIEW

File: packages/api/src/database.ts [hunk 1]
```diff
@@ -169,15 +169,17 @@ export class DatabaseInstance {
       const roundSummaryData = {
         contributionCount: summary.contributionCount,
         uniqueContributors: summary.uniqueContributors,
-        totalContributionsInUSD: Number(summary.totalContributionsInUSD),
-        averageUSDContribution: Number(summary.averageUSDContribution),
+        totalContributionsInUSD: Number(summary.totalContributionsInUSD) ? Number(summary.totalContributionsInUSD) : 0,
+        averageUSDContribution: Number(summary.averageUSDContribution) ? Number(summary.averageUSDContribution) : 0,
```
Comment (thelostone-mc) [inline packages/api/src/database.ts:173]: ^ Why is this needed ? 
The default value for summary.totalContributionsInUSD and summary.averageUSDContribution is 0 
Why would we have anything else here ?

**Comment by melissa-neira** [comment]
defer to engineering 🦋

File: packages/api/src/database.ts (hunk 1 above)
Comment (hmrtn) [reply packages/api/src/database.ts:173]: I added this and forgot to remove it as a sanity check.

**Review by vacekj — APPROVED** [review]
