### PR TITLE
chore(lint): rewrite function to fix no async promise executor error

### LINKED ISSUE #374: refactor to comply with eslint no-async-promise-executor rule
we should (in a separate chore/pr) refactor this so it does follow the rule. [eslint documentation](https://eslint.org/docs/latest/rules/no-async-promise-executor ) has some good reasons why the rule should be followed, and i don't think it would be too difficult to update the code here

_Originally posted by @shavinac in https://github.com/gitcoinco/grants-round/pull/347#discussion_r968799232_

### PR DESCRIPTION
**Pull request by vacekj**
##### Description

fixed async executor function

##### Refers/Fixes

#374 

##### Testing

no new code was introduced

### CODE REVIEW

File: packages/round-manager/src/features/api/services/grantApplication.ts [hunk 1]
```diff
@@ -11,24 +11,22 @@ import {
 import { Web3Provider } from "@ethersproject/providers";
 import { Signer } from "@ethersproject/abstract-signer";
 
-const updateApplicationList = (
+const updateApplicationList = async (
   applications: GrantApplication[],
   roundId: string,
   provider: Web3Provider
 ): Promise<string> => {
   /* ESLint ignore is fine since we handle the throws*/
```
Comment (shavinac) [inline packages/round-manager/src/features/api/services/grantApplication.ts:19]:
```suggestion
```

**Review by shavinac — APPROVED** [review]
